// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'user_model.mapper.dart';

@MappableClass()
class UserModel with UserModelMappable{

  UserModel({required this.userId, required this.name ,required this.email, required this.phone, required this.notificationId ,required this.joinedDate});

  final String userId;
  final String name;
  final String email;
  final String phone; 
  
  @MappableField(key: 'notification_id')
  final String notificationId;

   @MappableField(key: 'joined_date')
  final DateTime joinedDate;
}