// ignore_for_file: public_member_api_docs, sort_constructors_first
// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'order_model.mapper.dart';


@MappableClass()
class OrderModel with OrderModelMappable {

    OrderModel({
    required this.orderId,
    required this.userId,
    required this.totalPrice,
    required this.status,
    required this.orderDate,
    required this.address,
    required this.latitude,
    required this.longitude,
  });

  @MappableField(key: 'order_id')
  final String orderId;

  @MappableField(key: 'user_id')
  final String userId;

  @MappableField(key: 'total_price')
  final double totalPrice;

  final String status;

  @MappableField(key: 'order_date')
  final String orderDate;

  final String address;

  final double latitude;

  final double longitude;


}

